version: '3.5'
services:
  db_mysql:
    image: mysql:5.7
    container_name: witsoft-mysql-service
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: witsoft
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - core_service_network
  db_mongo:
    image: mongo:4.4.18
    container_name: witsoft-mongo-service
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/configdb
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - core_service_network
    command: ["/usr/local/bin/docker-entrypoint.sh", "mongod"]
  mongo_express:
    image: mongo-express
    container_name: witsoft-mongo-express-service
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: witsoft-mongo-service
      ME_CONFIG_MONGODB_PORT: "27017"
    depends_on:
      - db_mongo
    networks:
      - core_service_network
  # api:
  #   container_name: witsoft-api-service
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #     - .env.${NODE_ENV}
  #   depends_on:
  #     - db_mysql
  #     - db_mongo
  #   ports:
  #     - 80:${PORT}
  #   volumes:
  #     - api_data:/usr/src/app
  #   networks:
  #     - core_service_network
networks:
  core_service_network:
    driver: bridge
    name: witsoft_service_network
volumes:
  mysql_data:
    name: witsoft_mysql_data
  mongo_data:
    name: witsoft_mongo_data
  api_data:
    name: witsoft_api_data
