version: '3.5'
services:
  db_mongo:
    image: mongo:4.4.18
    container_name: witsoft-mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/configdb
      - mongo_data:/data/db
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - core_network
    command: [ "sh", "-c", "/usr/local/bin/docker-entrypoint.sh mongod"]
  mongo_express:
    image: mongo-express:1.0.0-alpha.4
    container_name: witsoft-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: witsoft-mongo-db
      ME_CONFIG_MONGODB_PORT: ${DB_PORT}
    depends_on:
      - db_mongo
    networks:
      - core_network
  api:
    container_name: witsoft-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST: 0.0.0.0
      DB_HOST: witsoft-mongo-db
    env_file:
      - .env.${NODE_ENV}
    depends_on:
      - db_mongo
    ports:
      - 8080:${PORT}
    networks:
      - core_network
networks:
  core_network:
    driver: bridge
    name: witsoft_network
volumes:
  mongo_data:
    name: witsoft_mongo_data
