 export const ARGUMENT_INVALID = 'GENERIC.ARGUMENT_INVALID';
 export const ARGUMENT_NOT_PROVIDED = 'GENERIC.ARGUMENT_NOT_PROVIDED';
 export const ARGUMENT_OUT_OF_RANGE = 'GENERIC.ARGUMENT_OUT_OF_RANGE';
 export const BAD_REQUEST = 'GENERIC.BAD_REQUEST';
 export const CONFLICT = 'GENERIC.CONFLICT';
 export const INTERNAL_SERVER_ERROR = 'GENERIC.INTERNAL_SERVER_ERROR';
 export const NOT_FOUND = 'GENERIC.NOT_FOUND';
 export const UNPROCESSABLE_ENTITY = 'GENERIC.UNPROCESSABLE_ENTITY';
